apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
data:
  MONGODB_HOST: "mongodb.mongodb"
  MONGODB_DATABASE_CREDENTIALS: "admin"
  MONGODB_USERNAME: "root"
  MONGODB_PASSWORD: "yourmongodbpassword"
  MONGODB_DATABASE_STORAGE: "KerberosStorage"
