apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factory
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: factory
    spec:
      containers:
      - name: factory
        image: "kerberos/factory:1.0.910553312" # or you can use "kerberos/factory:latest"
        #imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: mongodb
        # Injecting the ca-certificates inside the container.
        #volumeMounts:
        #- name: rootcerts
        #  mountPath: /etc/ssl/certs/ca-certificates.crt
        #  subPath: ca-certificates.crt
        env:
        - name: GIN_MODE
          value: release
        - name: KERBEROS_LOGIN_USERNAME
          value: "root"
        - name: KERBEROS_LOGIN_PASSWORD
          value: "kerberos"

        - name: KERBEROS_AGENT_IMAGE
          value: "kerberos/agent:384448d"
        - name: KERBEROS_AGENT_MEMORY_LIMIT
          value: "256Mi"

        # Do not touch this, unless you know what you are doing.
        - name: NAMESPACE
          value: "kerberos-factory"
        - name: FACTORY_ENVIRONMENT
          value: "kubernetes"
        - name: K8S_PROXY
          value: http://localhost:80

        # Additional certificates can be injected into the Kerberos Agents, through the creation of a configmap. 
        # A certificate "ca-certificates.crt" is expected in the configmap, and will be added to
        # the Kerberos Agent in following directory: /etc/ssl/certs/
        #- name: CERTIFICATES_CONFIGMAP
        #  value: "rootcerts" 
      #volumes:
      #- name: rootcerts
      #  configMap:
      #    name: rootcerts
---
apiVersion: v1
kind: Service
metadata:
  name: factory-lb
  labels:
    app: factory
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: frontend
    protocol: TCP
  selector:
    app: factory
